/**
 * Builds the scroll sequence from the 24 source JPGs:
 *  - interpolates to 120 frames (crossfade-blended in-betweens) → public/sequence/vespa_[i]_exploded.webp
 *  - samples the background color at the frame edges → lib/frameColors.ts
 *    (the sequence moves from a dark gallery to a light studio, so the page
 *     background must follow the frames, not a single fixed color)
 */
import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC_DIR = "ezgif-6916fc1b9fff21ef-jpg";
const OUT_DIR = "public/sequence";
const TOTAL_FRAMES = 120;
const WIDTH = 1920;
const HEIGHT = 1080;
const QUALITY = 62;

const sources = (await readdir(SRC_DIR))
  .filter((f) => f.endsWith(".jpg"))
  .sort()
  .map((f) => path.join(SRC_DIR, f));

if (sources.length < 2) throw new Error(`Expected source frames in ${SRC_DIR}`);
console.log(`Interpolating ${sources.length} source frames → ${TOTAL_FRAMES} webp frames`);

await mkdir(OUT_DIR, { recursive: true });

const rawCache = new Map();
async function raw(srcPath) {
  if (!rawCache.has(srcPath)) {
    rawCache.set(
      srcPath,
      await sharp(srcPath).resize(WIDTH, HEIGHT).raw().toBuffer()
    );
  }
  return rawCache.get(srcPath);
}

function blend(a, b, t) {
  const out = Buffer.allocUnsafe(a.length);
  for (let i = 0; i < a.length; i++) {
    out[i] = Math.round(a[i] + (b[i] - a[i]) * t);
  }
  return out;
}

/** average color of the left+right edge strips at mid height — this is what
 *  letterbox bars sit against, so it's the color the page must match */
function sampleEdges(buf) {
  const strip = 12;
  let r = 0, g = 0, b = 0, n = 0;
  const yStart = Math.floor(HEIGHT * 0.3);
  const yEnd = Math.floor(HEIGHT * 0.7);
  for (let y = yStart; y < yEnd; y += 4) {
    for (let x = 0; x < strip; x++) {
      for (const xx of [x, WIDTH - 1 - x]) {
        const i = (y * WIDTH + xx) * 3;
        r += buf[i]; g += buf[i + 1]; b += buf[i + 2]; n++;
      }
    }
  }
  r = Math.round(r / n); g = Math.round(g / n); b = Math.round(b / n);
  const hex = `#${[r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
  const luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
  return { hex, luminance: Math.round(luminance * 1000) / 1000 };
}

const colors = [];
const limit = 6;
let active = 0;
const queue = [];
const run = (fn) =>
  new Promise((resolve, reject) => {
    const task = async () => {
      active++;
      try { resolve(await fn()); } catch (e) { reject(e); }
      active--;
      if (queue.length) queue.shift()();
    };
    active < limit ? task() : queue.push(task);
  });

await Promise.all(
  Array.from({ length: TOTAL_FRAMES }, (_, i) =>
    run(async () => {
      // palindromic timeline: the source footage only disassembles, but the
      // story needs a reassembly — explode until 60% of scroll, rebuild after
      const p = i / (TOTAL_FRAMES - 1);
      const t01 = p <= 0.6 ? p / 0.6 : (1 - p) / 0.4;
      const pos = t01 * (sources.length - 1);
      const lo = Math.floor(pos);
      const hi = Math.min(lo + 1, sources.length - 1);
      const t = pos - lo;

      const a = await raw(sources[lo]);
      const buf = t < 0.001 ? a : blend(a, await raw(sources[hi]), t);

      colors[i] = sampleEdges(buf);
      await sharp(buf, { raw: { width: WIDTH, height: HEIGHT, channels: 3 } })
        .webp({ quality: QUALITY, effort: 4 })
        .toFile(path.join(OUT_DIR, `vespa_${i}_exploded.webp`));
      process.stdout.write(`\rframe ${i}`);
    })
  )
);

await mkdir("lib", { recursive: true });
await writeFile(
  "lib/frameColors.ts",
  `// Auto-generated by scripts/process-frames.mjs — per-frame edge background color.
export const TOTAL_FRAMES = ${TOTAL_FRAMES};
export const FRAME_COLORS: { hex: string; luminance: number }[] = ${JSON.stringify(colors)};
`
);
console.log(`\nDone: ${TOTAL_FRAMES} frames + lib/frameColors.ts`);
